/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    store "github.com/myname/myrepo/pkg/store"
	//
	store "github.com/antoinedao/aecdelta-go-server/pkg/store"

)

// UsersGet - 
func UsersGet(c *gin.Context) {
	// Run Auth checks here

	// Run data store operation
	// `resource` must be of type map[string]interface{}
	resource, err := store.UsersGet(c)

	if err != nil {
		c.AbortWithStatusJSON(err.StatusCode(), err)
	}

	c.JSON(http.StatusOK, resource)
}

// UsersIdGet - 
func UsersIdGet(c *gin.Context) {
	// Run Auth checks here

	// Run data store operation
	// `resource` must be of type map[string]interface{}
	resource, err := store.UsersIdGet(c)

	if err != nil {
		c.AbortWithStatusJSON(err.StatusCode(), err)
	}

	c.JSON(http.StatusOK, resource)
}
