/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


// MergePayload - A payload to configure a merge operation between two streams
type MergePayload struct {

	From string `json:"from"`
}
