/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


type Permission string

// List of Permission
const (
	READ Permission = "read"
	WRITE Permission = "write"
	ADMIN Permission = "admin"
)
