/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


// ProjectRole - An individual role for a project. Note that a role with null permissions cannot access the resource.
type ProjectRole struct {

	Name string `json:"name"`

	Permission map[string]interface{} `json:"permission"`

	TeamRoles TeamRole `json:"team_roles"`
}
