/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

//package openapi
package model

// StreamRole - An individual role for a stream. Note that a role with null permissions cannot access the resource.
type StreamRole struct {

	Name string `json:"name"`

	Permission map[string]interface{} `json:"permission"`

	ProjectRoles ProjectRole1 `json:"project_roles"`
}
