/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

//package openapi
package model

// Revision - A single revision for a stream
type Revision struct {

	StreamId string `json:"stream_id"`

	ProjectId string `json:"project_id"`

	// UTC format
	Datetime string `json:"datetime"`

	Author Author `json:"author"`

	Payload map[string]interface{} `json:"payload"`
}
