/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

//package openapi
package model

// Revisions - A list of revisions for a stream
type Revisions struct {

	StreamId string `json:"stream_id"`

	Description string `json:"description,omitempty"`

	ProjectId string `json:"project_id"`

	Revisions []string `json:"revisions"`
}
