/*
 * aecdeltas
 *
 * The AEC Deltas OpenAPI Spec
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

//package openapi
package model

// BranchPayload - A payload to configure a branch operation from a stream
type BranchPayload struct {

	Options NewStream `json:"options"`
}
